### ISSUE TITLE
Trying to run 2 TI 1843 parallelly, but one shuts down when I run the other

### ISSUE THREAD

**Issue by senguptaa** [cstahoviak/radar_rig#1]
Hi Carl,

I actually came across your post on TI's forum about trying to run two radars on ROS simultaneously, and that you were able to get that to work. I tried namespaces - but for some reason launching the 2nd radar shuts down the first one. Would you have some advice/guidance on what I can change in the source codes to get this to work? Or is there a repo that I can refer to? Thanks!

**Comment by cstahoviak** [comment]
Hi Arindam, I'm glad you found my post in the E2E forum and my repo here. I have a private `ti_mmwave_rospkg` repo that I can share with you where I have solved the problem of running two TI radars simultaneously. Please let me know if that would still be helpful, or if you have been able to solve the problem on your own.

**Comment by senguptaa** [comment]
Hi Carl,

Thank you for getting back! I think I might have figured it out. But thanks anyways. I will reach out just in case my approach doesn;t work.
